{% set version = "16.17.0" %}

# NODE_MODULE_VERSION set in src/node_version.h
{% set NODE_MODULE_VERSION = 93 %}

package:
  name: nodejs
  version: {{ version }}

source:
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [not win]
  sha256: 2a2e6262739741f98ab81648a50891861dbf66f12413b93f1a97b4c71570611e  # [not win]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: 4731da4fbb2015d414e871fa9118cabb643bdb6dbdc8a69a3ed563266ac93229  # [win]
  patches:
    - linux-librt.patch  # [not win]
    - cinttypes.patch  # [linux]
    - less-shared-intermediate.patch  # [build_platform != target_platform]
    - 0001-Forward-ceilf-floorf.patch  # [not win]
    - 0001-Force-include-handler-outside-simulator.patch  # [osx and arm64]
    - aarch64-trap-handler.patch  # [linux and aarch64]

build:
  number: 0
  # Prefix replacement breaks in the binary embedded configurations.
  detect_binary_files_with_prefix: false
  run_exports:
    - {{ pin_subpackage('nodejs', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - sysroot_linux-64 2.17  # [linux64]
    - python 3.8  # [not win]
    - git  # [linux]
    - ninja  # [not win]
    - pkg-config  # [not win]

    # need host builds of several lib dependencies
    # when cross-compiling
    - icu  # [build_platform != target_platform]
    - libuv  # [build_platform != target_platform]
    - openssl  # [build_platform != target_platform]
    - zlib  # [build_platform != target_platform]
  host:
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  run:
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  run_constrained:   # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]
    - test -f $PREFIX/lib/libnode.{{ NODE_MODULE_VERSION }}.dylib  # [osx]
    - test -f $PREFIX/lib/libnode.so.{{ NODE_MODULE_VERSION }}  # [linux]

about:
  home: https://nodejs.org/
  license: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
