bot:
  abi_migration_branches:
  - 12.x
  - 14.x
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
conda_forge_output_validation: true
provider:
  win: default
conda_build:
  pkg_format: '2'
test: native_and_emulated
